### PR TITLE
Move to use node-fetch for node support

### PR DESCRIPTION
**Pull request by hcjk**
## Summary

This PR updates the fetch library used to load data using the `node-fetch` library instead of the `fetch-jsonp` library. This allows us to provide support for node implementations, as previously this would throw an error stating that `window` is not defined inside of the `fetch-jsonp` library.

## Changes

- Add the `node-fetch` library and switch libraries.
- Update the webpack config to ensure that the `node-fetch` library is built when compiled.

Issue: #1

### CODE REVIEW

**Comment by hcjk** [comment]
Sorry about the delay on this one, but let me know if you have any questions. I ran tests locally and everything passed. Also installed my version of the library and tested it both in node and the browser, both working.

**Comment by giladaya** [comment]
@hcjk thanks for the PR, can you make sure that the example is working?
Also - I think that the axios dependency is not needed.

**Comment by hcjk** [comment]
@giladaya Good catch, just fixed that. I ran the example locally and it worked. Would you be able to verify that as well just for redundancy?

**Comment by giladaya** [comment]
It seems that now google allows cross-origin requests without the use of jsonp so that dependency can be dropped completely in favour of plain `fetch`.

**Pull request merged**
